[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[scheduled]]
  function = "keep-warm"
  schedule = "*/5 * * * *"

[[edge_functions]]
  function = "hello"
  path = "/api/hello"
