[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[scheduled]]
  function = "keep-warm"
  schedule = "*/5 * * * *"

[[scheduled]]
  function = "licenseNotify"
  schedule = "0 1,13 * * *" # 8AM + 8PM Thailand time (UTC+7)

[[edge_functions]]
  function = "hello"
  path = "/api/hello"

[[edge_functions]]
  function = "projects-proxy"
  path = "/api/edge-projects"
